/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Asus-PC
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuVendedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuMoto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuPuntoVenta = new javax.swing.JMenuItem();
        MenuVenta = new javax.swing.JMenu();
        MenuRegistrar = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        MenuAnuales = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        MenuPV = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        MenuV = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        MnuSalir = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Proyecto Final Programación Multinivel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        MenuAdmin.setText("Administrar");

        MenuCliente.setText("Cliente");
        MenuAdmin.add(MenuCliente);
        MenuAdmin.add(jSeparator1);

        MenuVendedor.setText("Vendedor");
        MenuAdmin.add(MenuVendedor);
        MenuAdmin.add(jSeparator2);

        MenuMoto.setText("Moto");
        MenuMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMotoActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuMoto);
        MenuAdmin.add(jSeparator3);

        MenuPuntoVenta.setText("Punto de Venta");
        MenuPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPuntoVentaActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuPuntoVenta);

        jMenuBar1.add(MenuAdmin);

        MenuVenta.setText("Venta");

        MenuRegistrar.setText("Registrar");
        MenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarActionPerformed(evt);
            }
        });
        MenuVenta.add(MenuRegistrar);

        jMenuBar1.add(MenuVenta);

        MenuReportes.setText("Reporte");

        MenuAnuales.setText("Anuales");
        MenuAnuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAnualesActionPerformed(evt);
            }
        });
        MenuReportes.add(MenuAnuales);
        MenuReportes.add(jSeparator5);

        jMenu5.setText("Diarias");

        MenuPV.setText("Punto de Venta");
        MenuPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPVActionPerformed(evt);
            }
        });
        jMenu5.add(MenuPV);
        jMenu5.add(jSeparator6);

        MenuV.setText("Vendedor");
        MenuV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVActionPerformed(evt);
            }
        });
        jMenu5.add(MenuV);

        MenuReportes.add(jMenu5);

        jMenuBar1.add(MenuReportes);

        MenuSalir.setText("Salir");

        MnuSalir.setText("Salir");
        MenuSalir.add(MnuSalir);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMotoActionPerformed
        
    }//GEN-LAST:event_MenuMotoActionPerformed

    private void MenuPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPuntoVentaActionPerformed
        
    }//GEN-LAST:event_MenuPuntoVentaActionPerformed

    private void MenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarActionPerformed
        
    }//GEN-LAST:event_MenuRegistrarActionPerformed

    private void MenuAnualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAnualesActionPerformed
        
    }//GEN-LAST:event_MenuAnualesActionPerformed

    private void MenuPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPVActionPerformed
        
    }//GEN-LAST:event_MenuPVActionPerformed

    private void MenuVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVActionPerformed
        
    }//GEN-LAST:event_MenuVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new vista().setVisible(true);
        });
    }

    public JMenu getMenuAdmin() {
        return MenuAdmin;
    }

    public void setMenuAdmin(JMenu MenuAdmin) {
        this.MenuAdmin = MenuAdmin;
    }

    public JMenuItem getMenuAnuales() {
        return MenuAnuales;
    }

    public void setMenuAnuales(JMenuItem MenuAnuales) {
        this.MenuAnuales = MenuAnuales;
    }

    public JMenuItem getMenuCliente() {
        return MenuCliente;
    }

    public void setMenuCliente(JMenuItem MenuCliente) {
        this.MenuCliente = MenuCliente;
    }

    public JMenuItem getMenuMoto() {
        return MenuMoto;
    }

    public void setMenuMoto(JMenuItem MenuMoto) {
        this.MenuMoto = MenuMoto;
    }

    public JMenuItem getMenuPV() {
        return MenuPV;
    }

    public void setMenuPV(JMenuItem MenuPV) {
        this.MenuPV = MenuPV;
    }

    public JMenuItem getMenuPuntoVenta() {
        return MenuPuntoVenta;
    }

    public void setMenuPuntoVenta(JMenuItem MenuPuntoVenta) {
        this.MenuPuntoVenta = MenuPuntoVenta;
    }

    public JMenuItem getMenuRegistrar() {
        return MenuRegistrar;
    }

    public void setMenuRegistrar(JMenuItem MenuRegistrar) {
        this.MenuRegistrar = MenuRegistrar;
    }

    public JMenu getMenuReportes() {
        return MenuReportes;
    }

    public void setMenuReportes(JMenu MenuReportes) {
        this.MenuReportes = MenuReportes;
    }

    public JMenu getMenuSalir() {
        return MenuSalir;
    }

    public void setMenuSalir(JMenu MenuSalir) {
        this.MenuSalir = MenuSalir;
    }

    public JMenuItem getMenuV() {
        return MenuV;
    }

    public void setMenuV(JMenuItem MenuV) {
        this.MenuV = MenuV;
    }

    public JMenuItem getMenuVendedor() {
        return MenuVendedor;
    }

    public void setMenuVendedor(JMenuItem MenuVendedor) {
        this.MenuVendedor = MenuVendedor;
    }

    public JMenu getMenuVenta() {
        return MenuVenta;
    }

    public void setMenuVenta(JMenu MenuVenta) {
        this.MenuVenta = MenuVenta;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuAdmin;
    public javax.swing.JMenuItem MenuAnuales;
    public javax.swing.JMenuItem MenuCliente;
    public javax.swing.JMenuItem MenuMoto;
    public javax.swing.JMenuItem MenuPV;
    public javax.swing.JMenuItem MenuPuntoVenta;
    public javax.swing.JMenuItem MenuRegistrar;
    public javax.swing.JMenu MenuReportes;
    public javax.swing.JMenu MenuSalir;
    public javax.swing.JMenuItem MenuV;
    public javax.swing.JMenuItem MenuVendedor;
    public javax.swing.JMenu MenuVenta;
    public javax.swing.JMenuItem MnuSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
